# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03f98c9d8a1513853d3e64ac9247cbbb387024565fbec945395628cc4a41e5344644a11e8482d42d6806d8867bea14b41192caf75c940e0be3cd2b8a34bdcf20

test:
  secret_key_base: 0c7fb0db6b42f3c0f2ffc3dc0a613f6e53e0d9a1c5d6b835c7f73e1ee2b6307a28a4d64b8ac5f4a4a3f30285fc8481b718a012df1e756e7e8adc873025328756

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
